route: support for retrieving a link's permanent address.
thom311/libnl pull request #362
Opened 2023-10-02 09:50 UTC by NailAgliev

Not sure about libnl-route-3.sym. Please check.

2023-10-27 14:20 UTC, thom311 requested changes

2023-10-27 14:20 UTC, thom311 commented on libnl-route-3.sym
> +	rtnl_link_get_perm_addr;
3.8 is already released. That means the section "libnl_3_8" must not be changed anymore.

Add a new `libnl_3_9` section at the bottom of the file.

2023-10-27 14:20 UTC, thom311 commented on lib/route/link.c
> +struct nl_data *rtnl_link_get_perm_addr(struct rtnl_link *link)
compare to `rtnl_link_get_addr`. That one returns a `struct nl_addr` type. I think that should also be used for the perm-addr, or why not?

2023-10-27 14:20 UTC, thom311 commented on lib/route/link.c
> +			addr[3], addr[4], addr[5]);
cannot blindly access the `addr` array. Must make sure that there are 6 elements there (and do something in case there isn't).

2023-10-27 14:20 UTC, thom311 commented on lib/route/link.c
> +			return -NLE_NOMEM;
please squash the commits. This second commit just fixes a bug in the previous commit.

2023-10-27 14:20 UTC, thom311 commented on lib/route/nl-route.h
> +	struct nl_data * perm_addr;
also needs to be handled in `link_compare()`.

2024-03-04 18:05 UTC, NailAgliev commented
I'm sorry for keeping the flow-up delayed. I'm hoping to complete this feature soon.

Any updates that should be taken into consideration after the release of 3.9?

2024-03-04 19:50 UTC, thom311 commented
> I'm sorry for keeping the flow-up delayed. I'm hoping to complete this feature soon.

Don't worry. Contribute at the pace that works best for you. Thank you!

> Any updates that should be taken into consideration after the release of 3.9?

No? I think I don't understand the question.

2024-03-04 20:52 UTC, NailAgliev commented
Sorry for confusing question. I meant to ask if there something a should take into account while implementing requested changes.  For example in [libnl-route-3.sym](https://github.com/thom311/libnl/pull/362/files/9b88a7f5e2b90ab7e60a7de2030f32ec86eeefe7#diff-febaa7415c8b650a4afb9d2b91715f2343d31171c2a0b0f8ccbf9b3a4519d5e6)  section libnl_3_9 already exist due to release of 3.9, so i should name new section 3.10 right?

2024-03-05 06:35 UTC, thom311 commented
> libnl_3_9 already exist due to release of 3.9, so i should name new section 3.10 right?

Yes, the section to be extended is the one from the next (future) release. At this time, that is `libnl_3_10`. Note that this section already exists. Make sure to rebase your patch on top of current `main`.

2024-10-30 06:51 UTC, thom311 commented
A similar feature was in the meantime implemented in commit acf572b585361587740b7c80ed33b3df2706ece9 (#404).

Closing this.

Thank you for your efforts!

2024-10-30 06:51 UTC, closed without merging